question_data = [
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Entertainment: Music",
            "text": "Green Day&#039;s album &#039;American Idiot&#039; is considered a &quot;punk rock opera.&quot;",
            "answer": "True",
            "inanswers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Entertainment: Music",
            "text": "Rapper Snoop Dogg&#039;s real name is &#039;Cordozar Calvin Broadus, Jr.&#039;.",
            "answer": "True",
            "inanswers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Entertainment: Music",
            "text": "Pink Guy&#039;s debut album was &quot;Pink Season&quot;.",
            "answer": "False",
            "inanswers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Entertainment: Music",
            "text": "Nick Mason is the only member to appear on every Pink Floyd album.",
            "answer": "True",
            "inanswers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Entertainment: Music",
            "text": "3 members of 2 Live Crew were arrested for playing songs from their album, As Nasty As They Wanna Be, live.",
            "answer": "True",
            "inanswers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Entertainment: Music",
            "text": "&quot;Neutral Milk Hotel&quot; is a real band.",
            "answer": "True",
            "inanswers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Entertainment: Music",
            "text": "Soulja Boy&#039;s &#039;Crank That&#039; won a Grammy for Best Rap Song in 2007.",
            "answer": "False",
            "inanswers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Entertainment: Music",
            "text": "Musical artist, Future, collaborated with Kendrick Lamar for the song: &quot;Mask Off&quot;.",
            "answer": "True",
            "inanswers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Entertainment: Music",
            "text": "&quot;The Division Bell&quot; is the final album of the progressive rock band Pink Floyd.",
            "answer": "False",
            "inanswers": ["True"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Entertainment: Music",
            "text": "The country song  &ldquo;A Boy Named Sue&rdquo; was written by Shel Silverstein.",
            "answer": "True",
            "inanswers": ["False"],
        },
]