SCREEN_SIZE_WIDTH = 600
SCREEN_SIZE_HEIGHT = 600
SCREEN_SIZE_WIDE_MIN = -300
SCREEN_SIZE_WIDE_MAX = 300
SCREEN_SIZE_HEIGHT_MIN = -300
SCREEN_SIZE_HEIGHT_MAX = 300
STARTING_CAR_COUNT = 15

STARTING_POSITION = (0, -280)
MOVE_DISTANCE = 10
FINISH_LINE_Y = 280

FONT = ("Courier", 24, "normal")

COLORS = ["red", "orange", "yellow", "green", "blue", "purple"]
STARTING_MOVE_DISTANCE = 5
MOVE_INCREMENT = 10